version: '3'

services:
  airbyte-webapp:
    image: airbyte/webapp:0.50.48
    ports:
      - "80:80"
    depends_on:
      - airbyte-server

  airbyte-server:
    image: airbyte/server:0.50.48
    ports:
      - "8001:8001"
    environment:
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=airbyte
      - DATABASE_URL=jdbc:postgresql://airbyte-db:5432/airbyte
    depends_on:
      - airbyte-db

  airbyte-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=airbyte
      - POSTGRES_DB=airbyte
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
